typography_spectrum: 0.3868867
color:
  saturation: 0.7852234
  lightness: 0.8083705
  brandStrength: 0.03035956
  rhythmicContrast: 0.901883
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
layout_spectrum: 0.138251
name: Luc Herlitz
title: all about Luc
description: whether you cared or not
